import type { Assets } from '../../src/core/assets';
import { Game } from '../../src/game/game';
import { LEVELS } from '../../src/game/config';
import { cellCenterX, rowFootY } from '../../src/game/grid';
import { loadBattleSave, restoreBattle, saveBattle } from '../../src/game/save';
import { pauseButtonsRect } from '../../src/game/ui';
import type { CheckResult } from './reward-flow-entry';

export function storyChecks(assets: Assets): CheckResult[] {
  const out: CheckResult[] = [];
  const check = (name: string, ok: boolean): void => { out.push({ name, ok }); };
  const finish = (game: Game): void => { while (game.eggDialogue !== null) game.advanceEggDialogue(); };
  const first = new Game(assets, LEVELS[0]);
  first.dough = 100;
  first.placing = 'douxian_shooter';
  first.cooldowns.set('hemian_doubao', 4);
  first.onPointerDown({ x: cellCenterX(0), y: rowFootY(2) - 40 });
  first.update(10);
  check('普通关开场对话冻结波次、资源和冷却，阻止种植', first.time === 0 && first.doughTimer === 0 && first.dough === 100 && first.cooldowns.get('hemian_doubao') === 4 && !first.defenders.length && !first.attackers.length);
  check('一行关只在中间草坪放置推车', first.mowers.length === 1 && first.mowers[0].row === 2);
  first.advanceEggDialogue();
  first.advanceEggDialogue(true);
  check('普通关翻页与回看保留同一战场', first.eggDialogue === 0 && first.time === 0 && first.dough === 100);
  first.advanceEggDialogue();
  saveBattle(first);
  const saved = loadBattleSave()!;
  const resumed = restoreBattle(assets, saved);
  check('普通关读档保留对话页码并先暂停', resumed.eggDialogue === 1 && resumed.pauseOpen);
  const button = pauseButtonsRect().cont;
  resumed.onPointerDown({ x: button.x + 20, y: button.y + 20 });
  resumed.update(5);
  check('续战点继续回到未读完的对话，战场仍冻结', !resumed.pauseOpen && resumed.eggDialogue === 1 && resumed.time === 0);
  finish(resumed);
  resumed.update(0.2);
  check('读完普通关对话后资源与冷却恢复推进', resumed.time === 0.2 && resumed.doughTimer > 0 && resumed.cooldowns.get('hemian_doubao')! < 4);
  saveBattle(resumed);
  check('完成对话的续战不会重复播放开场', restoreBattle(assets, loadBattleSave()!).eggDialogue === null);
  delete saved.eggDialogue;
  saved.mowers.push({ row: 0, x: 0, y: rowFootY(0), state: 'idle', t: 0 });
  const legacy = restoreBattle(assets, saved);
  check('旧普通关存档无需重读开场，清除裸土上的推车', legacy.eggDialogue === null && legacy.mowers.length === 1 && legacy.mowers[0].row === 2);
  const second = new Game(assets, LEVELS[1]);
  finish(second);
  second.dough = 100;
  second.placing = 'douxian_shooter';
  second.onPointerDown({ x: cellCenterX(0), y: rowFootY(0) - 40 });
  check('三行关裸土不可种植，保留所选卡和面团', second.defenders.length === 0 && second.placing === 'douxian_shooter' && second.dough === 100);
  second.onPointerDown({ x: cellCenterX(0), y: rowFootY(1) - 40 });
  check('三行关草坪可种植，只有三台对应推车', second.defenders.length === 1 && second.defenders[0].row === 1 && second.dough === 0 && second.mowers.map((m) => m.row).join(',') === '1,2,3');
  const conveyor = new Game(assets, LEVELS[9]);
  const positions = conveyor.conveyor!.cards.map((c) => c.x).join(',');
  conveyor.update(30);
  check('传送带教学期间供卡与移动冻结', conveyor.time === 0 && conveyor.conveyor!.cards.map((c) => c.x).join(',') === positions);
  check('十关均有豆包对话，第五关保留四页节奏教学', LEVELS.every((level) => new Game(assets, level).story.length >= 2) && new Game(assets, LEVELS[4]).story.length === 4);
  return out;
}
